apiVersion: v1
kind: ServiceAccount
metadata:
  name: heartbeat
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  namespace: default
  labels:
    app: heartbeat
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
  selector:
    app: heartbeat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: heartbeat
  name: heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeat
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: heartbeat
    spec:
      serviceAccountName: heartbeat
      containers:
        - name: heartbeat
          image: localhost:5001/heartbeat-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: PORT
              value: '9001'
