apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: dashboard-to-heartbeat
spec:
  destination:
    name: heartbeat
  sources:
    - name: dashboard
      action: allow
