global:
  enabled: true
  name: consul
  image: localhost:5001/consul-enterprise:local
  datacenter: dc1

  tls:
    enabled: true

  acls:
    manageSystemACLs: true

  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"

  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'

server:
  enabled: true

ui:
  enabled: true
  service:
    type: NodePort

connectInject:
  enabled: true
  metrics:
    defaultEnableMerging: true
